name: ESPHome Theme
license: MIT
licenselink: https://github.com/esphome/esphome-docs/LICENSE.md
description: Custom theme for ESPHome documentation
homepage: https://esphome.io/
tags:
  - documentation
  - responsive
features:
  - responsive
  - search
  - syntax highlighting
min_version: 0.80.0
